name: apps
services:
  api:
    image: ${API_IMAGE:-ghcr.io/atrakic/azure-go-app}:${API_RELEASE:-0.0.3}
    container_name: api
    environment:
      VIRTUAL_PORT: ${API_VIRTUAL_PORT:-5000}
      VIRTUAL_HOST: ${API_VIRTUAL_HOST:-api.localhost}
      LETSENCRYPT_HOST: ${API_LETSENCRYPT_HOST:-}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "/usr/bin/wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    expose:
      - ${API_VIRTUAL_PORT:-5000}
