services:
  # https://github.com/nginx-proxy/acme-companion/blob/main/docs/Docker-Compose.md#two-containers-example
  nginx-proxy:
    image: nginxproxy/nginx-proxy:${NGINX_PROXY_RELEASE:-1.4}
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NO_COLOR=1
    volumes:
      # The vhost and conf volumes are only required
      # if you plan to obtain standalone certificates
      # - vhost:/etc/nginx/vhost.d
      # - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  acme-companion:
    image: nginxproxy/acme-companion:${ACME_RELEASE:-latest}
    container_name: nginx-proxy-acme
    restart: always
    env_file:
      - .env
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL:-foo@bar.org}
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  # https://containrrr.dev/watchtower/
  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_RELEASE:-latest}
    container_name: watchtower
    restart: always
    command: |
      --cleanup
      --interval 3600
      --http-api-update
      --http-api-metrics
      --http-api-periodic-polls
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      WATCHTOWER_HTTP_API_TOKEN: "${WATCHTOWER_HTTP_API_TOKEN:-'$$RANDOM'}"
      WATCHTOWER_NOTIFICATION_URL: "${WATCHTOWER_NOTIFICATION_URL:-}"
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATIONS_LEVEL: "${WATCHTOWER_NOTIFICATIONS_LEVEL:-info}"
      VIRTUAL_PORT: ${WATCHTOWER_VIRTUAL_PORT:-8080}
      VIRTUAL_HOST: ${WATCHTOWER_VIRTUAL_HOST:-watchtower.local}
      LETSENCRYPT_HOST: ${WATCHTOWER_LETSENCRYPT_HOST:-}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - proxy

volumes:
  # vhost:
  # conf:
  html:
  certs:
  acme:

networks:
  proxy:
    external: true
