services:
  api:
    image: ${API_IMAGE:-nginx}:${API_RELEASE:-alpine}
    container_name: api
    restart: always
    environment:
      # https://github.com/atrakic/azure-webapp-golang/blob/a63e26b3d2a37f1b99b4da710abead77a1dd7b05/src/main.go#L19
      PORT: ${API_VIRTUAL_PORT:-80}
      VIRTUAL_PORT: ${API_VIRTUAL_PORT:-80}
      VIRTUAL_HOST: ${API_VIRTUAL_HOST:-api.local}
      LETSENCRYPT_HOST: ${API_LETSENCRYPT_HOST:-}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy
    expose:
      - ${API_VIRTUAL_PORT:-80}

networks:
  proxy:
    driver: bridge
