services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:${NGINX_PROXY_RELEASE:-1.6}
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NO_COLOR=1
    volumes:
      # The vhost volume is only required if you
      # plan to obtain standalone certificates
      # - vhost:/etc/nginx/vhost.d
      #- conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/config/nginx.conf:/etc/nginx/conf.d/my_proxy.conf:ro

  letsencrypt:
    image: nginxproxy/acme-companion:${ACME_RELEASE:-latest}
    container_name: letsencrypt
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL:-mail@yourdomain.tld}
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_RELEASE:-latest}
    container_name: watchtower
    restart: unless-stopped
    command: |
      --interval 86400
      --http-api-update
      --http-api-metrics
      --http-api-periodic-polls
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LETSENCRYPT_HOST: ${WATCHTOWER_LETSENCRYPT_HOST:-}
      VIRTUAL_HOST: ${WATCHTOWER_VIRTUAL_HOST:-watchtower.localhost}
      VIRTUAL_PORT: ${WATCHTOWER_VIRTUAL_PORT:-8080}
      WATCHTOWER_HTTP_API_TOKEN: ${WATCHTOWER_HTTP_API_TOKEN:-a55fab18d2466e18}
      #WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_NOTIFICATION_URL:-}
      #- WATCHTOWER_ROLLING_RESTART=true
      #- WATCHTOWER_NOTIFICATIONS=msteams
      #- WATCHTOWER_NOTIFICATION_MSTEAMS_USE_LOG_DATA=true
      #- WATCHTOWER_NOTIFICATION_MSTEAMS_HOOK_URL="https://outlook.office.com/webhook/xxxxxxxx@xxxxxxx/IncomingWebhook/yyyyyyyy/zzzzzzzzzz" \
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    expose:
      - ${WATCHTOWER_VIRTUAL_PORT:-8080}

volumes:
  conf:
  #vhost:
  html:
  certs:
  acme:
