name: monitoring

services:
  grafana:
    build:
      context: ./docker/monitoring/grafana/
    container_name: grafana
    user: "104"
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
      - ./docker/monitoring/grafana/config/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./docker/monitoring/grafana/config/config.monitoring
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    environment:
      VIRTUAL_HOST: ${GRAFANA_VIRTUAL_HOST:-grafana.localhost}
      VIRTUAL_PORT: ${GRAFANA_PORT:-3000}
      LETSENCRYPT_HOST: ${GRAFANA_LETSENCRYPT_HOST:-}
      LETSENCRYPT_EMAIL: ${GRAFANA_LETSENCRYPT_EMAIL:-}
    expose:
      - ${GRAFANA_PORT:-3000}

  prometheus:
    build:
      context: ./docker/monitoring/prometheus/
    container_name: prometheus
    volumes:
      - ./docker/monitoring/prometheus/config/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-14d}'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    environment:
      VIRTUAL_PORT: ${PROMETHEUS_VIRTUAL_PORT:-9090}
      VIRTUAL_HOST: ${PROMETHEUS_VIRTUAL_HOST:-prometheus.localhost}
      LETSENCRYPT_HOST: ${PROMETHEUS_LETSENCRYPT_HOST:-}
    depends_on:
      - cadvisor
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    expose:
      - ${PROMETHEUS_VIRTUAL_PORT:-9090}

  cadvisor:
    build:
      context: ./docker/monitoring/cadvisor/
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    expose:
      - 8080

  alertmanager:
    build:
      context: ./docker/monitoring/alertmanager/
    container_name: alertmanager
    volumes:
      - ./docker/monitoring/alertmanager/config/:/etc/alertmanager/
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"

  node-exporter:
    build:
      context: ./docker/monitoring/node-exporter/
    container_name: node-exporter
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    #network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'

volumes:
  prometheus:
  grafana:
