name: monitoring

services:
  grafana:
    build:
      context: monitoring/grafana/
    container_name: grafana
    user: "104"
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
      - ./monitoring/grafana/config/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./monitoring/grafana/config/config.monitoring
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    environment:
      - VIRTUAL_HOST=${GRAFANA_VIRTUAL_HOST:-}
      - VIRTUAL_PORT=${GRAFANA_PORT:-3000}
      - LETSENCRYPT_HOST=${GRAFANA_LETSENCRYPT_HOST:-}
      - LETSENCRYPT_EMAIL=${GRAFANA_LETSENCRYPT_EMAIL:-}
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    networks:
      - monitoring
      - default

  prometheus:
    build:
      context: monitoring/prometheus/
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/config/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-14d}'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - cadvisor
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    networks:
      - monitoring

  cadvisor:
    build:
      context: monitoring/cadvisor/
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    networks:
      - monitoring

  alertmanager:
    build:
      context: monitoring/alertmanager/
    container_name: alertmanager
    volumes:
      - ./monitoring/alertmanager/config/:/etc/alertmanager/
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    networks:
      - monitoring

  node-exporter:
    build:
      context: monitoring/node-exporter/
    container_name: node-exporter
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    networks:
      - monitoring

volumes:
  prometheus:
  grafana:

networks:
  monitoring:
  default:
    external: true
    name: proxy
