name: Azure Deployment

on:
  workflow_dispatch:

jobs:
  azure-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Infrastructure
        run: |
          cd /infra
          make
