name: Docker Compose CI

on:
  push:
  pull_request:

env:
  APP: api

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the stack
        run: |
          export COMPOSE_FILE=compose.yml:compose.sut.yml
          docker network create proxy
          DOCKER_BUILDKIT=1 docker compose up --quiet-pull --no-color --remove-orphans --exit-code-from ${{ env.APP }}
